# Generated by Django 3.2.1 on 2021-05-19 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_text', models.CharField(max_length=200)),
                ('phonics', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_text', models.CharField(max_length=200)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madlibs.master')),
            ],
        ),
    ]
