# Generated by Django 3.2.1 on 2021-05-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madlibs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='phonics',
            new_name='story_name',
        ),
        migrations.AddField(
            model_name='textentry',
            name='phonics',
            field=models.CharField(default='Placeholder text', max_length=200),
            preserve_default=False,
        ),
    ]
