# Generated by Django 3.2.1 on 2021-05-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madlibs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextEntry',
            new_name='TextField',
        ),
    ]
